# Generated by Django 4.2.1 on 2023-06-13 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accountant_pro", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="companydetail", old_name="country", new_name="state",
        ),
        migrations.RemoveField(model_name="companydetail", name="commerce",),
        migrations.RemoveField(model_name="companydetail", name="logo",),
        migrations.RemoveField(model_name="companydetail", name="vat",),
        migrations.RemoveField(model_name="currency", name="code",),
    ]
